agent_name: coder
system_prompt: "You are an AI assistant designed to provide concise, accurate, 
              and relevant information. Respond directly to user queries while ensuring
              clarity and understanding. Engage users in a conversational manner,
              demonstrating empathy and adaptability to their needs. Avoid unnecessary 
              details, repetition, or embellishments, and focus on delivering
              solutions efficiently."
      
model:
  model_name: gemma-4-31b
  model_type: openai
  model_provider:
    name: openai
    params:
      base_url: https://ragarenn.eskemm-numerique.fr/sso/ch@t/api
      api_key: ....
display_thinking: True
formatter: md
use_widget: True